default:
  tags: [talpa-fargate-webx]

stages:
  - release

variables:
  AWS_REGION: eu-west-1

publishContentTypes:
  stage: release
  # rules:
  #   - if: $CI_COMMIT_TAG
  #     when: on_success
  when: manual
  script:
    - dutils header "Publishing content types"
    - |
      echo "@4tn:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
      echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
